// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN48JPJ-NIuBxvc5IfMFZf9evMsYzIKEg',
    appId: '1:780860598498:web:68e48d36d691e647d416bb',
    messagingSenderId: '780860598498',
    projectId: 'gym-app-firebase-79daf',
    authDomain: 'gym-app-firebase-79daf.firebaseapp.com',
    storageBucket: 'gym-app-firebase-79daf.firebasestorage.app',
    measurementId: 'G-5S8Q487HKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMccDDZbRfp8RkXkC7JMAaDuwBfuMvHwg',
    appId: '1:780860598498:android:10a7e6a1a1b9262dd416bb',
    messagingSenderId: '780860598498',
    projectId: 'gym-app-firebase-79daf',
    storageBucket: 'gym-app-firebase-79daf.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN48JPJ-NIuBxvc5IfMFZf9evMsYzIKEg',
    appId: '1:780860598498:web:e547e5e7354b2b48d416bb',
    messagingSenderId: '780860598498',
    projectId: 'gym-app-firebase-79daf',
    authDomain: 'gym-app-firebase-79daf.firebaseapp.com',
    storageBucket: 'gym-app-firebase-79daf.firebasestorage.app',
    measurementId: 'G-SK8YR3CF5G',
  );
}